import * as path from 'path';
import * as fs from 'fs/promises';
import { TicketService } from './ticket.service';
import { IndexService } from './index.service';
import type { Ticket, TicketIndex } from '../models/ticket.model';
import { CURRENT_TICKET_FILE } from '../utils/constants';

export class AIService {
  private ticketService: TicketService;
  private indexService: IndexService;
  private workspaceRoot: string;

  constructor(
    ticketService: TicketService,
    indexService: IndexService,
    workspaceRoot: string,
  ) {
    this.ticketService = ticketService;
    this.indexService = indexService;
    this.workspaceRoot = workspaceRoot;
  }

  /**
   * Get structured JSON context for a single ticket.
   * Designed for consumption by AI tools.
   */
  async getTicketContext(id: string): Promise<string | null> {
    const ticket = await this.ticketService.getTicket(id);
    if (!ticket) {
      return null;
    }

    return JSON.stringify(
      {
        id: ticket.frontmatter.id,
        title: ticket.frontmatter.title,
        status: ticket.frontmatter.status,
        priority: ticket.frontmatter.priority,
        assignees: ticket.frontmatter.assignees,
        labels: ticket.frontmatter.labels,
        description: ticket.description,
        acceptanceCriteria: ticket.acceptanceCriteria,
        branch: ticket.frontmatter.branch,
        linkedCommits: ticket.frontmatter.linkedCommits,
        comments: ticket.comments.map((c) => ({
          timestamp: c.timestamp,
          author: c.author,
          body: c.body,
        })),
        createdAt: ticket.frontmatter.createdAt,
        updatedAt: ticket.frontmatter.updatedAt,
        createdBy: ticket.frontmatter.createdBy,
      },
      null,
      2,
    );
  }

  /**
   * Get structured JSON context for all tickets.
   * Designed for consumption by AI tools.
   */
  async getAllTicketsContext(): Promise<string> {
    const index = await this.indexService.getIndex();

    return JSON.stringify(
      {
        totalTickets: index.tickets.length,
        lastUpdated: index.lastUpdated,
        tickets: index.tickets.map((t) => ({
          id: t.id,
          title: t.title,
          status: t.status,
          priority: t.priority,
          assignees: t.assignees,
          updatedAt: t.updatedAt,
        })),
        byStatus: groupByStatus(index),
      },
      null,
      2,
    );
  }

  /**
   * Link the current git branch to a ticket.
   */
  async linkBranchToTicket(
    ticketId: string,
    branchName: string,
  ): Promise<void> {
    await this.ticketService.updateTicket(ticketId, {
      branch: branchName,
    } as any);
  }

  /**
   * Generate current ticket context file based on branch name.
   * Writes CURRENT_TICKET.md at the workspace root (gitignored).
   * Always writes deterministic content (never deletes the file).
   *
   * Three states:
   * 1. Ticket found -- full ticket context
   * 2. No ticket ID in branch -- "no ticket detected" message
   * 3. Ticket ID found but ticket file missing -- "ticket not found" message
   *
   * Reads ticket data through TicketService (worktree-aware).
   */
  async generateCurrentTicketContext(
    branchName: string,
    ticketId: string | null,
  ): Promise<void> {
    let markdownContent: string;

    if (!ticketId) {
      markdownContent = buildNoTicketContent(branchName);
    } else {
      const ticket = await this.ticketService.getTicket(ticketId);

      if (!ticket) {
        markdownContent = buildTicketNotFoundContent(branchName, ticketId);
      } else {
        markdownContent = buildTicketContextContent(branchName, ticket);
      }
    }

    const filePath = path.join(this.workspaceRoot, CURRENT_TICKET_FILE);
    await fs.writeFile(filePath, markdownContent, 'utf-8');
  }
}

// ---------------------------------------------------------------------------
// Content builders
// ---------------------------------------------------------------------------

function buildTicketContextContent(branchName: string, ticket: Ticket): string {
  const fm = ticket.frontmatter;
  const lines: string[] = [
    '<!-- Auto-generated by Opentix. Do not edit. Gitignored. -->',
    `# Current Ticket: ${fm.id}`,
    '',
    `**Branch**: ${branchName}`,
    `**Title**: ${fm.title}`,
    `**Status**: ${formatStatus(fm.status)}`,
  ];

  if (fm.sprint) {
    lines.push(`**Sprint**: ${fm.sprint}`);
  }

  lines.push(`**Priority**: ${fm.priority}`);

  if (fm.assignees.length > 0) {
    lines.push(`**Assignees**: ${fm.assignees.join(', ')}`);
  }

  if (fm.labels.length > 0) {
    lines.push(`**Labels**: ${fm.labels.join(', ')}`);
  }

  lines.push('');

  if (ticket.description) {
    lines.push('## Description', '', ticket.description.trim(), '');
  }

  if (ticket.acceptanceCriteria) {
    lines.push('## Acceptance Criteria', '', ticket.acceptanceCriteria.trim(), '');
  }

  if (ticket.comments.length > 0) {
    lines.push('## Comments', '');
    for (const comment of ticket.comments) {
      lines.push(`### ${comment.timestamp} | ${comment.author}`, '', comment.body.trim(), '');
    }
  }

  return lines.join('\n');
}

function buildNoTicketContent(branchName: string): string {
  return `<!-- Auto-generated by Opentix. Do not edit. Gitignored. -->
# No Ticket Detected

No ticket ID found on current branch \`${branchName}\`.

Check \`.opentix/tickets/\` for all available tickets, or ensure your branch
name contains a ticket ID (e.g., \`feat/OPTX-0001-description\`).
`;
}

function buildTicketNotFoundContent(branchName: string, ticketId: string): string {
  return `<!-- Auto-generated by Opentix. Do not edit. Gitignored. -->
# Ticket Not Found: ${ticketId}

Ticket \`${ticketId}\` referenced in branch \`${branchName}\` but not found
in \`.opentix/tickets/\`. It may not have been created yet.

Create the ticket via the Opentix board or check \`.opentix/tickets/\` for
available tickets.
`;
}

function groupByStatus(
  index: TicketIndex,
): Record<string, number> {
  const groups: Record<string, number> = {};
  for (const ticket of index.tickets) {
    groups[ticket.status] = (groups[ticket.status] || 0) + 1;
  }
  return groups;
}

function formatStatus(status: string): string {
  return status
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}
